"""Generate coverage from tags; --check fails on stale committed output."""
import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]


def render():
    reference = json.loads((ROOT / 'docs/attack-reference.json').read_text())
    rows = []
    tactics = set()
    correlation_count = 0
    mapped = 0
    paths = sorted((ROOT / 'rules').rglob('*.yml')) + sorted((ROOT / 'correlations').glob('*.yml'))
    for path in paths:
        rule = yaml.safe_load(path.read_text())
        correlation_count += int('correlation' in rule)
        tags = {tag[7:] for tag in rule.get('tags', []) if tag.startswith('attack.')}
        rule_tactics = sorted(tags & reference['tactics'].keys())
        mapped += int(bool(rule_tactics))
        tactics.update(rule_tactics)
        techniques = []
        for tag in sorted(tags - set(rule_tactics)):
            technique = reference['techniques'][tag.upper()]
            techniques.append(f"[{tag.upper()} {technique['name']}]({technique['url']})")
        link = f"[{rule['title']}](../{path.relative_to(ROOT).as_posix()})"
        rows.append(f"| {link} | {', '.join(reference['tactics'][t] for t in rule_tactics) or 'Unmapped hunting signal'} | {'; '.join(techniques) or 'None claimed'} | {rule['level']} |")
    missing = sorted(reference['tactics'].keys() - tactics)
    return ('# ATT&CK Mapping Inventory\n\n'
            'Generated by `python scripts/coverage.py`; edit rule tags and the reviewed reference snapshot, not this table.\n\n'
            f'{len(paths) - correlation_count} single-event selectors and {correlation_count} correlation(s); {mapped} documents carry ATT&CK mappings to {len(tactics)} of '
            f"{len(reference['tactics'])} current Enterprise tactics. This counts labels, not validated detection coverage. "
            'All rules are experimental. Unmapped hunting signals are excluded from tactic totals.\n\n'
            '| Rule | Tactic labels | Technique | Level |\n|---|---|---|---|\n' + '\n'.join(rows) + '\n\n'
            'No mapped rules for: ' + ', '.join(reference['tactics'][t] for t in missing) + '.\n\n'
            'Mapping is based on the MITRE STIX snapshot in [attack-reference.json](attack-reference.json). '
            'The current matrix separates Stealth and Defense Impairment; the former Defense Evasion label is not used. '
            'T1685.005 replaces revoked T1070.001; T1685 replaces revoked T1562.001. '
            'Recheck the snapshot against MITRE before adding or changing mappings.\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'docs/MITRE_COVERAGE.md'
    text = render()
    if args.check:
        assert path.read_text() == text, 'Coverage is stale; run python scripts/coverage.py'
        print('Generated ATT&CK coverage is current.')
    else:
        path.write_text(text)
        print('Wrote docs/MITRE_COVERAGE.md')


if __name__ == '__main__':
    main()
